# .github/workflows/preview.yml
name: deploy to development
on:
  push:
    branches:
      - 'staging'
    
  pull_request:
    branches: 
      - 'staging'
    types: 
      - 'closed'
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install
          rm package-lock.json
          yarn install

      - name: Build Application
        run: yarn build-storybook

  test:
    needs: build
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install
          rm package-lock.json
          yarn install

      - name: Run Tests
        run: yarn lint

  staging:
      if: github.event.pull_request.merged == true
      needs: [test]
      name: Deploy to staging
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        
        - name: Upload Storybook artifacts
          uses: actions/upload-artifact@v2
          with:
            name: storybook-artifacts
            path: storybook-static

        - name: Install Vercel CLI
          run: yarn global add vercel

        - name: Pull Vercel Environment Information
          run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

        - name: Build Project Artifacts
          run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

        - name: Deploy Project Artifacts to Vercel
          run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
    